// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailBank.Repositories;

#nullable disable

namespace RetailBank.Migrations
{
    [DbContext(typeof(RetailBankDBContext))]
    [Migration("20221214055248_RetailBank_1")]
    partial class RetailBank1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetailBank.Domain.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AmountDeducted")
                        .HasColumnType("float");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckOutId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTransactionId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("RetailBank.Domain.ShopperDetail", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardNumber");

                    b.ToTable("ShopperDetails");

                    b.HasData(
                        new
                        {
                            CardNumber = "378282246310005",
                            Balance = 200.0,
                            CVV = "123",
                            Currency = "USD",
                            ExpiryDate = "10/2023"
                        },
                        new
                        {
                            CardNumber = "371449635398431",
                            Balance = 200.0,
                            CVV = "456",
                            Currency = "EUR",
                            ExpiryDate = "10/2024"
                        },
                        new
                        {
                            CardNumber = "378734493671000",
                            Balance = 200.0,
                            CVV = "789",
                            Currency = "INR",
                            ExpiryDate = "10/2025"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
